// ORB keypoint detection and optical flow tracking used to detect turning during walk.
// A path is generated by assuming a const fwd step size, and accumulating the motion
// It compares this path to the ground truth from GPS data
// usage: ./generate_path Challenge_Set_Videos/Night_Walk/Night_Walk.MOV 30 50 Challenge_Set_Videos/Night_Walk/Night_Walk.csv
// to make a video from the output frames: ffmpeg -framerate 30 -i frames/frame_%05d.jpg output.mp4

#include <opencv2/opencv.hpp>
#include <opencv2/features2d.hpp>
#include <opencv2/video/tracking.hpp>
#include <iostream>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <vector>
#include <cmath>

static constexpr int MIN_TRACKS = 30; // need at least this many per frame, otherwise redetect
static constexpr int MAX_ORB = 500;
static constexpr bool SAVE_FRAMES = true;
static const std::string FRAME_DIR  = "frames";
static constexpr double FX = 2000.0; // focal length (dtheta = avg_dx / FX)
static constexpr double ALLOWABLE_DIST_ERR = 0.06; // metric for P and R calcs

// Helpers for reading in GPS data
struct GpsPt { double t, x, y; };
std::vector<GpsPt> load_gps(const std::string& path) {
    std::vector<GpsPt> pts;
    std::ifstream f(path);
    if (!f.is_open()) { std::cerr << "Can't open GPS CSV " << path << "\n"; return pts; }
    std::string line; std::getline(f, line); // skip header
    while (std::getline(f, line)) {
        GpsPt p;
        if (sscanf(line.c_str(), "%lf,%lf,%lf", &p.t, &p.x, &p.y) == 3) pts.push_back(p);
    }
    return pts;
}

double gps_path_length(const std::vector<GpsPt>& pts) { // total path length helps to get walking speed
    double len = 0;
    for (size_t i = 1; i < pts.size(); i++) {
        double dx = pts[i].x - pts[i-1].x; double dy = pts[i].y - pts[i-1].y;
        len += std::sqrt(dx*dx + dy*dy); // euclidean dist
    }
    return len;
}

// Draw both paths on top of each other to compare
// pass in full GPS path to lock the map bounds, otherwise the bounds will grow w vo and curr gps
cv::Mat draw_paths(const std::vector<GpsPt>& gps, const std::vector<GpsPt>& vo, int plot_size = 600, int margin = 60, const std::vector<GpsPt>* full_gps = nullptr) {
    // Scaling to fit on screen
    const std::vector<GpsPt>& bounds_src = full_gps ? *full_gps : gps;
    double min_x=1e9, max_x=-1e9, min_y=1e9, max_y=-1e9;
    for (auto& p : bounds_src) { min_x=std::min(min_x,p.x); max_x=std::max(max_x,p.x); min_y=std::min(min_y,p.y); max_y=std::max(max_y,p.y); }
    if (!full_gps) for (auto& p : vo) { min_x=std::min(min_x,p.x); max_x=std::max(max_x,p.x); min_y=std::min(min_y,p.y); max_y=std::max(max_y,p.y); }
    double pad = 0.05 * std::max(max_x-min_x, max_y-min_y);
    min_x -= pad; max_x += pad; min_y -= pad; max_y += pad;
    double range = std::max(max_x-min_x, max_y-min_y);
    if (range < 1e-6) range = 1.0;
    double sc = (plot_size - 2.0*margin) / range;
    auto to_px = [&](double x, double y) -> cv::Point {return { (int)(margin+(x-min_x)*sc), (int)(plot_size-margin-(y-min_y)*sc) };};
    cv::Mat img(plot_size, plot_size, CV_8UC3, cv::Scalar(30,30,30));

    // grid lines and dist labels
    for (int g = 0; g <= 5; g++) {
        int gx = margin+g*(plot_size-2*margin)/5, gy = margin+g*(plot_size-2*margin)/5;
        cv::line(img,{gx,margin},{gx,plot_size-margin},cv::Scalar(60,60,60),1);
        cv::line(img,{margin,gy},{plot_size-margin,gy},cv::Scalar(60,60,60),1);
        double wx = min_x + g * range / 5.0;
        cv::putText(img, cv::format("%.0f", wx), {gx-8, plot_size-margin+20}, cv::FONT_HERSHEY_SIMPLEX, 0.8, cv::Scalar(160,160,160), 1);
        double wy = min_y + (5-g) * range / 5.0;
        cv::putText(img, cv::format("%.0f", wy), {margin-30, gy+4}, cv::FONT_HERSHEY_SIMPLEX, 0.8, cv::Scalar(160,160,160), 1);
    }
    // axis titles
    cv::putText(img, "x (m)", {plot_size/2-20, plot_size-10}, cv::FONT_HERSHEY_SIMPLEX, 0.85, cv::Scalar(160,160,160), 1);
    cv::putText(img, "y (m)", {5, plot_size/2}, cv::FONT_HERSHEY_SIMPLEX, 0.85, cv::Scalar(160,160,160), 1);

    // gps data
    for (size_t i = 1; i < gps.size(); i++)
        cv::line(img, to_px(gps[i-1].x,gps[i-1].y), to_px(gps[i].x,gps[i].y), cv::Scalar(0,220,80), 2);
    if (!gps.empty()) {
        cv::circle(img, to_px(gps.front().x,gps.front().y), 7, cv::Scalar(0,255,0), -1);
        cv::circle(img, to_px(gps.back().x, gps.back().y),  7, cv::Scalar(0,140,0), -1);
    }
    cv::putText(img, "GPS ground truth", {margin,20}, cv::FONT_HERSHEY_SIMPLEX, 0.5, cv::Scalar(0,220,80),  1);

    // visual odometry data
    for (size_t i = 1; i < vo.size(); i++)
        cv::line(img, to_px(vo[i-1].x,vo[i-1].y), to_px(vo[i].x,vo[i].y), cv::Scalar(0,180,255), 2);
    if (!vo.empty()) {
        cv::circle(img, to_px(vo.front().x,vo.front().y), 7, cv::Scalar(0,200,255), -1);
        cv::circle(img, to_px(vo.back().x, vo.back().y),  7, cv::Scalar(0,100,180), -1);
    }
    cv::putText(img, "VO estimate", {margin,40}, cv::FONT_HERSHEY_SIMPLEX, 0.5, cv::Scalar(0,180,255), 1);

    return img;
}

// Frame pair visualization w map being drawn to the right
cv::Mat draw_frame_pair(const cv::Mat& prev_color, const cv::Mat& color, const std::vector<cv::Point2f>& good_prev_pts, const std::vector<cv::Point2f>& good_pts, const std::vector<int>& good_ids,
                        const std::vector<cv::Scalar>& PALETTE, const std::vector<GpsPt>& gps_so_far, const std::vector<GpsPt>& vo_so_far, const std::vector<GpsPt>& full_gps) {
    int W = color.cols, H = color.rows;
    int map_size = H;
    cv::Mat canvas(H, W * 2 + map_size, CV_8UC3, cv::Scalar(0,0,0));
    prev_color.copyTo(canvas(cv::Rect(0, 0, W, H))); // prev on left
    color.copyTo(canvas(cv::Rect(W, 0, W, H))); // curr in middle
    cv::Mat map_img = draw_paths(gps_so_far, vo_so_far, map_size, 50, &full_gps);
    map_img.copyTo(canvas(cv::Rect(W * 2, 0, map_size, map_size))); // map on right

    double sum_dx = 0, sum_dy = 0; // tracking displacement for average motion arrow
    for (size_t i = 0; i < good_pts.size(); i++) {
        cv::Scalar col = PALETTE[good_ids[i] % PALETTE.size()];
        cv::Point2f lp = good_prev_pts[i];
        cv::Point2f rp = good_pts[i] + cv::Point2f((float)W, 0);
        cv::circle(canvas, lp, 5, col, -1);
        cv::circle(canvas, rp, 5, col, -1);
        cv::line(canvas, lp, rp, col, 1);

        // add displacement for this keypoint
        sum_dx += good_pts[i].x - good_prev_pts[i].x;
        sum_dy += good_pts[i].y - good_prev_pts[i].y;
    }

    int num_tracks = (int)good_pts.size();
    // arrow for avg motion between frames
    if (num_tracks > 0) {
        double avg_dx = sum_dx / num_tracks;
        double avg_dy = sum_dy / num_tracks;
        cv::Point2f arrow_start((float)(W + W / 2), (float)(H / 2));
        float arrow_scale = -5.0f;
        cv::Point2f arrow_end(arrow_start.x + (float)(avg_dx * arrow_scale), arrow_start.y + (float)(avg_dy * arrow_scale));
        cv::arrowedLine(canvas, arrow_start, arrow_end, cv::Scalar(255, 255, 255), 3, cv::LINE_AA, 0, 0.3);
    }

    return canvas;
}

int main(int argc, char* argv[]) {
    if (argc < 5) {
        std::cerr << "Usage: " << argv[0] << " <video.mp4> <start_sec> <end_sec> <gps.csv>\n";
        return 1;
    }

    // load in video
    std::string video_path = argv[1];
    cv::VideoCapture cap(video_path);
    if (!cap.isOpened()) { std::cerr << "Can't open " << video_path << "\n"; return 1; }
    cv::setNumThreads(4); // parellize everything we can inside opencv
    double fps = cap.get(cv::CAP_PROP_FPS); double dt = 1.0 / fps;
    int total_frames = (int)cap.get(cv::CAP_PROP_FRAME_COUNT);
    double total_sec = total_frames / fps;

    double start_sec = (argc >= 3) ? std::stod(argv[2]) : 0.0;
    double end_sec = (argc >= 4) ? std::stod(argv[3]) : total_sec;
    int start_frame = (int)(start_sec * fps);
    int end_frame = (int)(end_sec * fps);
    cap.set(cv::CAP_PROP_POS_FRAMES, start_frame); // jump to start

    // csv gps data
    std::string gps_csv = argv[4];
    // calibrate forward speed from gps data
    std::vector<GpsPt> gps_pts = load_gps(gps_csv);
    double path_len = gps_path_length(gps_pts);
    double fwd_speed = path_len / (end_sec - start_sec); // mps average speed

    if (SAVE_FRAMES) std::filesystem::create_directories(FRAME_DIR); // build output dir

    // ORB and KLT setup
    auto orb = cv::ORB::create(MAX_ORB);
    std::vector<uchar> status;
    std::vector<float> err;
    std::vector<cv::KeyPoint> keypoints;
    // need diff keypoint colors, just stepping around color wheel
    const int N_COLORS = 20;
    std::vector<cv::Scalar> PALETTE;
    cv::Mat bgr;
    for (int i = 0; i < N_COLORS; i++) {
        cv::Mat hsv(1, 1, CV_8UC3, cv::Scalar(180 * i / N_COLORS, 220, 220));
        cv::cvtColor(hsv, bgr, cv::COLOR_HSV2BGR);
        auto* p = bgr.ptr<uint8_t>(0);
        PALETTE.push_back(cv::Scalar(p[0], p[1], p[2]));
    }
    std::vector<int> track_ids, good_ids;
    int next_id = 0;

    cv::Mat prev_gray, prev_color, gray, color;
    std::vector<cv::Point2f> prev_pts, good_prev_pts, curr_pts, good_pts; // where good points are the sucessfully tracked ones
    bool initialized = false;
    int frame_idx = start_frame;
    int saved_count = 0; // for ffmpeg output frame numbering
    int total_above = 0; // frames with >= MIN_TRACKS active tracks
    int total_counted = 0;

    // pose est from dead reckoning
    double x = 0, y = 0, theta = M_PI / 2.0; // start facing +Y in world frame
    std::vector<GpsPt> vo_pts; // visual odometry path points
    vo_pts.push_back({0.0, 0.0, 0.0});
    double last_logged_t = 0.0; // won't add every pnt to vo_pts, bc GPS is only 1hz

    // accuracy and speed metrics
    int TP = 0, FP = 0, FN = 0;
    int64 start_time = cv::getTickCount();

    while (true) {
        if (!cap.read(color) || color.empty()) break;
        if (frame_idx > end_frame) break;

        cv::cvtColor(color, gray, cv::COLOR_BGR2GRAY);
        double timestamp = (frame_idx - start_frame) / fps;

        int num_tracks = 0;
        // Detect orb keypoints
        if (!initialized || (int)prev_pts.size() < MIN_TRACKS) {
            std::printf("(redetecting)\n");
            orb->detect(gray, keypoints);
            prev_pts.clear(); track_ids.clear();
            cv::KeyPoint::convert(keypoints, prev_pts);
            // assign IDs to each point found
            for (size_t i = 0; i < prev_pts.size(); i++)
                track_ids.push_back(next_id++);
            prev_gray = gray.clone();
            prev_color = color.clone();
            initialized = true;
            frame_idx++;
            continue; // need two frames to track
        }

        // KLT optical flow
        good_pts.clear(); good_prev_pts.clear(); good_ids.clear(); status.clear(); err.clear();
        cv::calcOpticalFlowPyrLK(prev_gray, gray, prev_pts, curr_pts, status, err, cv::Size(21, 21), 3); // last two args are search window size and pyramid levels
        // filter to successfull tracks
        for (size_t i = 0; i < status.size(); i++) {
            if (status[i]){
                good_pts.push_back(curr_pts[i]);
                good_prev_pts.push_back(prev_pts[i]);
                good_ids.push_back(track_ids[i]);
            }
        }
        num_tracks = (int)good_pts.size();
        total_counted++;
        if (num_tracks >= MIN_TRACKS) total_above++;

        // Dead reckoning
        if (num_tracks > 0) {
            double sum_dx = 0;
            for (size_t i = 0; i < good_pts.size(); i++)
                sum_dx += good_pts[i].x - good_prev_pts[i].x;
            double avg_dx = sum_dx / num_tracks;
            double dtheta = avg_dx / FX; // radians
            theta += dtheta;

            // step forward at the const speed
            x += fwd_speed * dt * std::cos(theta); y += fwd_speed * dt * std::sin(theta);
        }
        if (timestamp - last_logged_t >= 1.0) {
            vo_pts.push_back({timestamp, x, y}); last_logged_t = timestamp;

            // Find closest GPS point to this time for err calcs
            int idx = (int)std::round(timestamp);
            GpsPt gps_now = gps_pts[std::min(idx, (int)gps_pts.size()-1)]; // clamp

            double err_x = x - gps_now.x; double err_y = y - gps_now.y; double dist_err = std::sqrt(err_x*err_x + err_y*err_y);
            float allowable_err = ALLOWABLE_DIST_ERR * path_len;
            std::printf("CURR ERR: %.2f percent     ", dist_err * 100.0 / path_len);
            if (num_tracks < MIN_TRACKS)
                FN++; // couldn't make reliable estimate
            else if (dist_err <= allowable_err)
                TP++; // estimate within x% of path length
            else
                FP++; // estimate made but too far off         
        }

        if (SAVE_FRAMES) {
            std::vector<GpsPt> gps_so_far;
            for (auto& g : gps_pts) if (g.t <= timestamp) gps_so_far.push_back(g); // only show gps points up to now
            cv::Mat canvas = draw_frame_pair(prev_color, color, good_prev_pts, good_pts, good_ids, PALETTE, gps_so_far, vo_pts, gps_pts);
            std::string filename = FRAME_DIR + "/frame_" + std::string(5 - std::to_string(saved_count).size(), '0') + std::to_string(saved_count) + ".jpg";
            cv::imwrite(filename, canvas);
            saved_count++;
        }

        // log
        if ((frame_idx - start_frame) % 30 == 0) {
            double survival = total_counted > 0 ? 100.0 * total_above / total_counted : 0.0;
            std::printf("frame %5d     t=%6.2fs      tracks=%3d     survival=%.1f%%    pos=(%.2f,%.2f)m\n", frame_idx, timestamp, num_tracks, survival, x, y);
        }

        // carry everything over
        prev_pts = good_pts;
        track_ids = good_ids;
        prev_gray = gray.clone();
        prev_color = color.clone();
        frame_idx++;
    }

    int64 end_time = cv::getTickCount();
    double elapsed_sec = (end_time - start_time) / cv::getTickFrequency();
    double avg_fps = total_counted / elapsed_sec;
    double precision = (TP + FP) ? (double)TP / (TP + FP) : 0.0;
    double recall = (TP + FN) ? (double)TP / (TP + FN) : 0.0;
    std::cout << "Average FPS: " << avg_fps << std::endl;
    std::cout << "TP: " << TP << ", FP: " << FP << ", FN: " << FN << std::endl;
    std::cout << "Precision: " << precision << std::endl;
    std::cout << "Recall: " << recall << std::endl;

    // Final path comparison plot
    cv::Mat path_img = draw_paths(gps_pts, vo_pts);
    std::string video_name = std::filesystem::path(video_path).stem().string();
    cv::imwrite(video_name + "_path.png", path_img);

    double survival = total_counted > 0 ? 100.0 * total_above / total_counted : 0.0;
    std::cout << "Done! Track survival rate: " << survival << "% " << "(" << total_above << "/" << total_counted << " frames)\n";
    std::printf("FINAL VO: (%.2f, %.2f) m\n", x, y);
    std::printf("FINAL GPS: (%.2f, %.2f) m\n", gps_pts.back().x, gps_pts.back().y);
    std::printf("FINAL ERR: (%.2f, %.2f) m\n", x - gps_pts.back().x, y - gps_pts.back().y);
    return 0;
}